### ISSUE TITLE
First try...

### ISSUE THREAD

**Issue by TChauvire** [samanvaya1/DLS_GUI#2]
Hello
I tried your test file after compiling the source code from Github.
I got this error in the command line window:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\tim_t\miniconda3\envs\dls\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
File "DLS_GUI.py", line 177, in LoadData
TypeError: 'ArtistList' object doesn't support item deletion

Any idea ? Apparently it's related to Plot_g2 object type and tkinter. The line mentioned contain the following code: 
del Plot_g2.lines[0]

Best

Timothee

Note: The compile file from your website works for windows.

**Comment by abhisheksriv87** [comment]
Hi @TChauvire ,

Thanks for your comment. Could you please share the version of python you are running as well as the python packages you have installed? (You could use the command 'pip list' on the command prompt)

**Comment by TChauvire** [comment]
So I create a conda envronement on a miniconda configuration. Python is 3.11.7
Here is the what I get from the pip list command:
Package                       Version
----------------------------- ------------
alabaster                     0.7.12
anyio                         4.2.0
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
asttokens                     2.0.5
async-lru                     2.0.4
atomicwrites                  1.4.0
attrs                         23.1.0
autopep8                      1.6.0
Babel                         2.11.0
bcrypt                        3.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         23.11.0
bleach                        4.1.0
Bottleneck                    1.3.7
Brotli                        1.0.9
certifi                       2024.2.2
cffi                          1.16.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.1.7
cloudpickle                   2.2.1
colorama                      0.4.6
comm                          0.1.2
contourpy                     1.2.0
cookiecutter                  2.5.0
cryptography                  42.0.2
cx_Freeze                     6.15.15
cx-Logging                    3.1.0
cycler                        0.11.0
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.7
docstring-to-markdown         0.11
docutils                      0.18.1
executing                     0.8.3
fastjsonschema                2.16.2
flake8                        6.0.0
fonttools                     4.25.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            7.0.1
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.28.0
ipython                       8.20.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
isort                         5.9.3
jaraco.classes                3.2.1
jedi                          0.18.1
jellyfish                     1.0.1
Jinja2                        3.1.3
json5                         0.9.6
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter                       1.0.0
jupyter_client                8.6.0
jupyter-console               6.6.3
jupyter_core                  5.5.0
jupyter-events                0.8.0
jupyter-lsp                   2.2.0
jupyter_server                2.10.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.11
jupyterlab-pygments           0.1.2
jupyterlab_server             2.25.1
jupyterlab-widgets            3.0.9
keyring                       23.13.1
kiwisolver                    1.4.4
lazy-object-proxy             1.6.0
lief                          0.14.0
markdown-it-py                2.2.0
MarkupSafe                    2.1.3
matplotlib                    3.8.0
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.0
mistune                       2.0.4
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
more-itertools                10.1.0
munkres                       1.1.4
mypy-extensions               1.0.0
nbclient                      0.8.0
nbconvert                     7.10.0
nbformat                      5.9.2
nest-asyncio                  1.6.0
notebook                      7.0.8
notebook_shim                 0.2.3
numexpr                       2.8.7
numpy                         1.26.3
numpydoc                      1.5.0
overrides                     7.4.0
packaging                     23.1
pandas                        2.1.4
pandocfilters                 1.5.0
paramiko                      2.8.1
parso                         0.8.3
pathspec                      0.10.3
patsy                         0.5.6
pexpect                       4.8.0
pickleshare                   0.7.5
pillow                        10.2.0
pip                           23.3.1
platformdirs                  3.10.0
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.43
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.10.0
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.0.1
Pygments                      2.15.1
pylint                        2.16.2
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyparsing                     3.0.9
PyQt5                         5.15.10
PyQt5-sip                     12.13.0
PyQtWebEngine                 5.15.6
PySocks                       1.7.1
python-dateutil               2.8.2
python-json-logger            2.0.7
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.2
python-slugify                5.0.2
pytoolconfig                  1.2.6
pytz                          2023.3.post1
pywavelets                    1.5.0
pywin32                       305.1
pywin32-ctypes                0.2.0
pywinpty                      2.0.10
PyYAML                        6.0.1
pyzmq                         25.1.2
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.2
QtPy                          2.4.1
referencing                   0.30.2
requests                      2.31.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.3.5
rope                          1.7.0
rpds-py                       0.10.6
Rtree                         1.0.1
scipy                         1.11.4
Send2Trash                    1.8.2
setuptools                    68.2.2
sip                           6.7.12
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.3
spyder-kernels                2.4.4
stack-data                    0.2.0
statsmodels                   0.14.1
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.2.1
three-merge                   0.1.1
tinycss2                      1.2.1
tk                            0.1.0
toml                          0.10.2
tomlkit                       0.11.1
tornado                       6.3.3
traitlets                     5.7.1
typing_extensions             4.9.0
tzdata                        2023.3
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       2.1.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
whatthepatch                  1.0.2
wheel                         0.41.2
widgetsnbextension            4.0.5
win-inet-pton                 1.1.0
wrapt                         1.14.1
yapf                          0.31.0
zipp                          3.17.0
----------------------------- ------------
And from conda list command:
----------------------------- ------------
Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0
anyio                     4.2.0           py311haa95532_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py311h2bbff1b_0
arrow                     1.2.3           py311haa95532_1
astroid                   2.14.2          py311haa95532_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-lru                 2.0.4           py311haa95532_0
atomicwrites              1.4.0                      py_0
attrs                     23.1.0          py311haa95532_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.11.0          py311haa95532_0
bcrypt                    3.2.0           py311h2bbff1b_1
beautifulsoup4            4.12.2          py311haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     23.11.0         py311haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
bottleneck                1.3.7           py311hd7041d2_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotli-python             1.0.9           py311hd77b12b_7
bzip2                     1.0.8                he774522_0
ca-certificates           2023.12.12           haa95532_0
certifi                   2024.2.2        py311haa95532_0
cffi                      1.16.0          py311h2bbff1b_0
chardet                   4.0.0           py311haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7           py311haa95532_0
cloudpickle               2.2.1           py311haa95532_0
colorama                  0.4.6           py311haa95532_0
comm                      0.1.2           py311haa95532_0
contourpy                 1.2.0           py311h59b6b97_0
cookiecutter              2.5.0           py311haa95532_0
cryptography              42.0.2          py311h89fc84f_0
cx-freeze                 6.15.15                  pypi_0    pypi
cx-logging                3.1.0                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.6.7           py311hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.7           py311haa95532_0
docstring-to-markdown     0.11            py311haa95532_0
docutils                  0.18.1          py311haa95532_3
executing                 0.8.3              pyhd3eb1b0_0
flake8                    6.0.0           py311haa95532_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
icc_rt                    2022.1.0             h6049295_2
icu                       73.1                 h6c2663c_0
idna                      3.4             py311haa95532_0
imagesize                 1.4.1           py311haa95532_0
importlib-metadata        7.0.1           py311haa95532_0
importlib_metadata        7.0.1                hd3eb1b0_0
inflection                0.5.1           py311haa95532_0
intel-openmp              2023.1.0         h59b6b97_46320
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.28.0          py311haa95532_0
ipython                   8.20.0          py311haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                8.0.4           py311haa95532_0
isort                     5.9.3              pyhd3eb1b0_0
jaraco.classes            3.2.1              pyhd3eb1b0_0
jedi                      0.18.1          py311haa95532_1
jellyfish                 1.0.1           py311h36a85e1_0
jinja2                    3.1.3           py311haa95532_0
jpeg                      9e                   h2bbff1b_1
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.19.2          py311haa95532_0
jsonschema-specifications 2023.7.1        py311haa95532_0
jupyter                   1.0.0           py311haa95532_9
jupyter-lsp               2.2.0           py311haa95532_0
jupyter_client            8.6.0           py311haa95532_0
jupyter_console           6.6.3           py311haa95532_0
jupyter_core              5.5.0           py311haa95532_0
jupyter_events            0.8.0           py311haa95532_0
jupyter_server            2.10.0          py311haa95532_0
jupyter_server_terminals  0.4.4           py311haa95532_1
jupyterlab                4.0.11          py311haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.25.1          py311haa95532_0
jupyterlab_widgets        3.0.9           py311haa95532_0
keyring                   23.13.1         py311haa95532_0
kiwisolver                1.4.4           py311hd77b12b_0
krb5                      1.20.1               h5b6d351_0
lazy-object-proxy         1.6.0           py311h2bbff1b_0
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libpng                    1.6.39               h8cc25b3_0
libpq                     12.17                h906ac69_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libtiff                   4.5.1                hd77b12b_0
libwebp-base              1.3.2                h2bbff1b_0
lief                      0.14.0                   pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_0
markdown-it-py            2.2.0           py311haa95532_1
markupsafe                2.1.3           py311h2bbff1b_0
matplotlib                3.8.0           py311haa95532_0
matplotlib-base           3.8.0           py311hf62ec03_0
matplotlib-inline         0.1.6           py311haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
mdurl                     0.1.0           py311haa95532_0
mistune                   2.0.4           py311haa95532_0
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0           py311h2bbff1b_1
mkl_fft                   1.3.8           py311h2bbff1b_0
mkl_random                1.2.4           py311h59b6b97_0
more-itertools            10.1.0          py311haa95532_0
munkres                   1.1.4                      py_0
mypy_extensions           1.0.0           py311haa95532_0
nbclient                  0.8.0           py311haa95532_0
nbconvert                 7.10.0          py311haa95532_0
nbformat                  5.9.2           py311haa95532_0
nest-asyncio              1.6.0           py311haa95532_0
notebook                  7.0.8           py311haa95532_0
notebook-shim             0.2.3           py311haa95532_0
numexpr                   2.8.7           py311h1fcbade_0
numpy                     1.26.3          py311hdab7c0b_0
numpy-base                1.26.3          py311hd01c5d8_0
numpydoc                  1.5.0           py311haa95532_0
openjpeg                  2.4.0                h4fc8c34_0
openssl                   3.0.13               h2bbff1b_0
overrides                 7.4.0           py311haa95532_0
packaging                 23.1            py311haa95532_0
pandas                    2.1.4           py311hf62ec03_0
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.10.3          py311haa95532_0
patsy                     0.5.6                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    10.2.0          py311h2bbff1b_0
pip                       23.3.1          py311haa95532_0
platformdirs              3.10.0          py311haa95532_0
pluggy                    1.0.0           py311haa95532_1
ply                       3.11            py311haa95532_0
prometheus_client         0.14.1          py311haa95532_0
prompt-toolkit            3.0.43          py311haa95532_0
prompt_toolkit            3.0.43               hd3eb1b0_0
psutil                    5.9.0           py311h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
pycodestyle               2.10.0          py311haa95532_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.3.0           py311haa95532_0
pyflakes                  3.0.1           py311haa95532_0
pygments                  2.15.1          py311haa95532_1
pylint                    2.16.2          py311haa95532_0
pylint-venv               2.3.0           py311haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pynacl                    1.5.0           py311h8cc25b3_0
pyparsing                 3.0.9           py311haa95532_0
pyqt                      5.15.10         py311hd77b12b_0
pyqt5-sip                 12.13.0         py311h2bbff1b_0
pyqtwebengine             5.15.10         py311hd77b12b_0
pysocks                   1.7.1           py311haa95532_0
python                    3.11.7               he1021f5_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py311haa95532_0
python-json-logger        2.0.7           py311haa95532_0
python-lsp-black          1.2.1           py311haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.7.2           py311haa95532_0
python-slugify            5.0.2              pyhd3eb1b0_0
python-tzdata             2023.3             pyhd3eb1b0_0
pytoolconfig              1.2.6           py311haa95532_0
pytz                      2023.3.post1    py311haa95532_0
pywavelets                1.5.0           py311hd7041d2_0
pywin32                   305             py311h2bbff1b_0
pywin32-ctypes            0.2.0           py311haa95532_1000
pywinpty                  2.0.10          py311h5da7b33_0
pyyaml                    6.0.1           py311h2bbff1b_0
pyzmq                     25.1.2          py311hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2           py311haa95532_0
qt-main                   5.15.2              h19c9488_10
qt-webengine              5.15.9               h5bd16bc_7
qtawesome                 1.2.2           py311haa95532_0
qtconsole                 5.4.2           py311haa95532_0
qtpy                      2.4.1           py311haa95532_0
referencing               0.30.2          py311haa95532_0
requests                  2.31.0          py311haa95532_1
rfc3339-validator         0.1.4           py311haa95532_0
rfc3986-validator         0.1.1           py311haa95532_0
rich                      13.3.5          py311haa95532_0
rope                      1.7.0           py311haa95532_0
rpds-py                   0.10.6          py311h062c2fa_0
rtree                     1.0.1           py311h2eaa2aa_0
scipy                     1.11.4          py311hc1ccb85_0
send2trash                1.8.2           py311haa95532_0
setuptools                68.2.2          py311haa95532_0
sip                       6.7.12          py311hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0           py311haa95532_0
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.5             py311haa95532_0
sphinx                    5.0.2           py311haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.4.3           py311haa95532_1
spyder-kernels            2.4.4           py311haa95532_0
sqlite                    3.41.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
statsmodels               0.14.1                   pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
terminado                 0.17.1          py311haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss2                  1.2.1           py311haa95532_0
tk                        0.1.0                    pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0
tomlkit                   0.11.1          py311haa95532_0
tornado                   6.3.3           py311h2bbff1b_0
traitlets                 5.7.1           py311haa95532_0
typing-extensions         4.9.0           py311haa95532_1
typing_extensions         4.9.0           py311haa95532_1
tzdata                    2023d                h04d1e81_0
ujson                     5.4.0           py311hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   2.1.0           py311haa95532_1
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.6           py311haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py311haa95532_1
websocket-client          0.58.0          py311haa95532_4
whatthepatch              1.0.2           py311haa95532_0
wheel                     0.41.2          py311haa95532_0
widgetsnbextension        4.0.5           py311haa95532_0
win_inet_pton             1.1.0           py311haa95532_0
winpty                    0.4.3                         4
wrapt                     1.14.1          py311h2bbff1b_0
xz                        5.4.5                h8cc25b3_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.5                hd77b12b_0
zipp                      3.17.0          py311haa95532_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

**Comment by abhisheksriv87** [comment]
@TChauvire I tried running the code with python 3.11.7 on Windows 10 and I was able to compile the executable without any errors. I got the following as a result of the pip list command.
![image](https://github.com/samanvaya1/DLS_GUI/assets/24664516/7b2afff8-50cc-48da-8d7d-6df81ba4d02c)

I also tried compiling with Python 3.10.5 and was able to do it without errors.

Perhaps you could retry the compilation in a new virtual environment?
